- name: Demo on variables
  hosts: localhost
  vars:
    URL: Facebook.com
  tasks:
    - name: Print URL variable
      ansible.builtin.debug:
        msg: "{{ URL }}"

- name: Demon on task Variables
  hosts: localhost
  tasks:
    - name: Print URl1 variable
      ansible.builtin.debug:
        msg: "{{ URL1 }}"
      vars:
        URL1: Facebook.com

- name: Register variable example
  hosts: localhost
  tasks:
      - name: get Uptime of server
        ansible.builtin.shell: uptime
        register: OUT
      - name: Print OUT var
        ansible.builtin.debug:
          msg: "{{ OUT }}"